export { AddIcon } from './Add';
export { AddressBookIcon } from './AddressBook';
export { AlarmClockIcon } from './AlarmClock';
export { AlignCenterIcon } from './AlignCenter';
export { AlignJustifyIcon } from './AlignJustify';
export { AlignLeftIcon } from './AlignLeft';
export { AlignRightIcon } from './AlignRight';
export { AmbulanceIcon } from './Ambulance';
export { AngleDoubleLeftIcon } from './AngleDoubleLeft';
export { AngleDoubleRightIcon } from './AngleDoubleRight';
export { AngleDoubleSmallLeftIcon } from './AngleDoubleSmallLeft';
export { AngleDoubleSmallRightIcon } from './AngleDoubleSmallRight';
export { AngleDownIcon } from './AngleDown';
export { AngleLeftIcon } from './AngleLeft';
export { AngleRightIcon } from './AngleRight';
export { AngleSmallDownIcon } from './AngleSmallDown';
export { AngleSmallLeftIcon } from './AngleSmallLeft';
export { AngleSmallRightIcon } from './AngleSmallRight';
export { AngleSmallUpIcon } from './AngleSmallUp';
export { AngleUpIcon } from './AngleUp';
export { AppleIcon } from './Apple';
export { AppsAddIcon } from './AppsAdd';
export { AppsDeleteIcon } from './AppsDelete';
export { AppsSortIcon } from './AppsSort';
export { AppsIcon } from './Apps';
export { ArchiveIcon } from './Archive';
export { ArrowDownIcon } from './ArrowDown';
export { ArrowFromBottomIcon } from './ArrowFromBottom';
export { ArrowLeftIcon } from './ArrowLeft';
export { ArrowRightIcon } from './ArrowRight';
export { ArrowSmallDownIcon } from './ArrowSmallDown';
export { ArrowSmallLeftIcon } from './ArrowSmallLeft';
export { ArrowSmallRightIcon } from './ArrowSmallRight';
export { ArrowSmallUpIcon } from './ArrowSmallUp';
export { ArrowUpIcon } from './ArrowUp';
export { AsteriskIcon } from './Asterisk';
export { AtIcon } from './At';
export { BackpackIcon } from './Backpack';
export { BadgeIcon } from './Badge';
export { BalloonsIcon } from './Balloons';
export { ContentCopyFilledIcon } from './ContentCopyFilled';
export { CheckFilledIcon } from './CheckFilled';
export { BanIcon } from './Ban';
export { BandAidIcon } from './BandAid';
export { BankIcon } from './Bank';
export { BarberShopIcon } from './BarberShop';
export { BaseballIcon } from './Baseball';
export { BasketballIcon } from './Basketball';
export { BedIcon } from './Bed';
export { BeerIcon } from './Beer';
export { BellIcon } from './Bell';
export { BellRingIcon } from './BellRing';
export { BellSchoolIcon } from './BellSchool';
export { BikeIcon } from './Bike';
export { BilliardIcon } from './Billiard';
export { BoldIcon } from './Bold';
export { BookAltIcon } from './BookAlt';
export { BookIcon } from './Book';
export { BookmarkIcon } from './Bookmark';
export { BowlingIcon } from './Bowling';
export { BoxIcon } from './Box';
export { BoxAltIcon } from './BoxAlt';
export { default as BreadSliceIcon } from './BreadSlice';
export { default as BriefcaseIcon } from './Briefcase';
export { default as BroomIcon } from './Broom';
export { default as BrowserIcon } from './Browser';
export { default as BrushIcon } from './Brush';
export { default as BugIcon } from './Bug';
export { default as BuildingIcon } from './Building';
export { default as BulbIcon } from './Bulb';
export { default as ButterflyIcon } from './Butterfly';
export { ClockIcon } from './Clock';

// New cake and call icons
export { default as CakeBirthdayIcon } from './CakeBirthday';
export { default as CakeWeddingIcon } from './CakeWedding';
export { default as CalculatorIcon } from './Calculator';
export { default as CalendarIcon } from './Calendar';
export { default as CallHistoryIcon } from './CallHistory';
export { default as CallIncomingIcon } from './CallIncoming';
export { default as CallMissedIcon } from './CallMissed';
export { default as CallOutgoingIcon } from './CallOutgoing';
export { default as CameraIcon } from './Camera';
export { default as CampingIcon } from './Camping';
export { default as CanParticipateIcon } from './CanParticipate';
export { default as CanPlayIcon } from './CanPlay';
export { default as CarIcon } from './Car';
export { default as CaravanIcon } from './Caravan';
export { default as CarrotIcon } from './Carrot';
export { default as CarSideIcon } from './CarSide';
export { default as CarwashIcon } from './Carwash';
export { default as CashIcon } from './Cash';
export { default as CatIcon } from './Cat';
export { default as CctvIcon } from './Cctv'; 